### ISSUE TITLE
Hook up Workforce DB

### ISSUE THREAD

**Issue by MattKraatz** [TeamCharles/customer-service#45]
### Feature Description
Employee and Department records need to be accessed via the Workforce_Management Database.

### Recommended Actions
>Refer to the [project requirements](https://github.com/TeamCharles/bangazon-inc/blob/master/projects/CUSTOMER_SERVICE_INCIDENTS.md) before filling out this section.

1. Create a new Bangazon Context file
1. Add a new environment variable pointing to that database
1. Update the ReadMe
1. Change the Employee and Department factories to refer to the new Bangazon Context
1. Debug any other issues that may arise from field names, parsing, etc.

**Comment by matthamil** [comment]
Resolved with https://github.com/TeamCharles/customer-service/pull/50
