### ISSUE TITLE
Update All Employee Calls with EndDate == null

### ISSUE THREAD

**Issue by MattKraatz** [TeamCharles/customer-service#48]
### Feature Description
Now that we have full Employee records from the workforce_management database, we need to update several different sections of this application to consider only current Employees (i.e. not fired).

### Recommended Actions
>Refer to the [project requirements](https://github.com/TeamCharles/bangazon-inc/blob/master/projects/CUSTOMER_SERVICE_INCIDENTS.md) before filling out this section.

Just need to add some filtering logic like: `WHERE EndDate IS NOT NULL`
1. Employee Factory
1. CreateEmployeeAction

**Comment by matthamil** [comment]
Resolved with https://github.com/TeamCharles/customer-service/pull/50
