### ISSUE TITLE
Create EmployeeFactory.cs with Get Employee and Set Employee

### ISSUE THREAD

**Issue by daynewright** [TeamCharles/customer-service#7]
### Feature Description
Create an `EmployeeFactory.cs` in the `Factories` folder.  

Create a singleton for the `ActiveEmployee`  to track logged in employee.
Create a method `GetEmployee(int id)` that takes the employee `id`

### Recommended Actions
>Refer to the [project requirements](https://github.com/TeamCharles/bangazon-inc/blob/master/projects/CUSTOMER_SERVICE_INCIDENTS.md) before filling out this section.

1.  Create file
2.  Create methods

**Comment by matthamil** [comment]
Resolved with #25
